apiVersion: v1
kind: Service
metadata:
  name: prod-microservice-service
spec:
  type: NodePort
  selector:
    app: prod-microservice
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007