apiVersion: v1
kind: Service
metadata:
  name: {{ include "prod-microservice.fullname" . }}
  labels:
    {{- include "prod-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "prod-microservice.name" . }}
